import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS GHA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sample <a href="https://docs.github.com/en/actions">Github Actions</a> Pipeline
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://docs.github.com/en/actions" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Github Actions.</p>
          </a>

          <a href="https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn on how to get started with Github Actions</p>
          </a>

          <a
            href="https://nextjs.org/docs/deployment"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>How to deploy NextJS App.</p>
          </a>

          <a
            href="https://aws.amazon.com/blogs/mobile/host-a-next-js-ssr-app-with-real-time-data-on-aws-amplify/"
            className={styles.card}
          >
            <h2>Deploy on AWS &rarr;</h2>
            <p>
              Documentation on how to deploy NextJS Apps on AWS.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
